FROM ubuntu:20.04 AS builder
WORKDIR /project
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && \
    apt-get -qq install -y cmake git vim gcc g++ gfortran software-properties-common wget gnupg-agent \
            python2 gnuplot-qt valgrind kcachegrind graphviz likwid gv localehelper \
            mpich libmpich-dev \
            openmpi-bin openmpi-doc libopenmpi-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#RUN curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
#RUN python2 get-pip.py

# Installing latest GCC compiler (version 10)
#RUN apt-get -qq update && \
#    apt-get -qq install -y gcc-10 g++-10 gfortran-10 && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/*

RUN locale-gen "en_US.UTF-8" && dpkg-reconfigure locales && update-locale LANG=en_US.UTF-8

RUN ls /usr/bin/python* #/usr/bin/pip*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python2 30
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 20
RUN python --version

# We are installing both OpenMPI and MPICH. We could use the update alternatives to switch between them
#RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90\
#                        --slave /usr/bin/g++ g++ /usr/bin/g++-10\
#                        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-10\
#                        --slave /usr/bin/gcov gcov /usr/bin/gcov-10

SHELL ["/bin/bash", "-c"]

RUN groupadd chapter3 && useradd -m -s /bin/bash -g chapter3 chapter3

WORKDIR /home/chapter3
RUN chown -R chapter3:chapter3 /home/chapter3
USER chapter3

RUN git clone --recursive https://github.com/essentialsofparallelcomputing/Chapter3.git
ENV LANG='en_US.UTF-8'

WORKDIR /home/chapter3

WORKDIR /home/chapter3/Chapter3
#RUN make

ENTRYPOINT ["bash"]
